config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'maps#index'

  post :explore, to: 'maps#explore'
end

app/models/brain.rb
# frozen_string_literal: true

class Brain
  def initialize(robot)
    @robot = robot
  end

  def east?
    @robot.side == :east
  end

  def max_x?
    @robot.x == @robot.plateau.x
  end

  def min_x?
    @robot.x == 0
  end

  def max_y?
    @robot.y == @robot.plateau.y
  end

  def min_y?
    @robot.y == 0
  end

  def north?
    @robot.side == :north
  end

  def south?
    @robot.side == :south
  end

  def west?
    @robot.side == :west
  end
end

app/models/gear.rb
# frozen_string_literal: true

class Gear
  def initialize(robot)
    @robot = robot
  end

  def turn_to(direction)
    return left  if direction.casecmp('l').zero?
    return right if direction.casecmp('r').zero?

    raise Errors::Gear::UnknowDirection, direction
  end

  private

  def left
    step sides[side_index == 0 ? sides.size - 1 : side_index - 1]
  end

  def right
    step sides[side_index < sides.size - 1 ? side_index + 1 : 0]
  end

  def sides
    @sides ||= @robot.plateau.sides
  end

  def step(side)
    @robot.side = side

    { side: @robot.side }
  end

  def side_index
    sides.index @robot.side.to_sym
  end
end

app/models/leg.rb
# frozen_string_literal: true

class Leg
  def initialize(robot)
    @robot = robot
  end

  def move
    send @robot.side
  end

  private

  def north
    max = @robot.brain.max_y?

    raise Errors::Plateau::OutOfLimit.new(@robot, __method__) if max

    step nil, 1
  end

  def east
    max = @robot.brain.max_x?

    raise Errors::Plateau::OutOfLimit.new(@robot, __method__) if max

    step 1, nil
  end

  def south
    min = @robot.brain.min_y?

    raise Errors::Plateau::OutOfLimit.new(@robot, __method__) if min

    step nil, -1
  end

  def step(x, y)
    @robot.x += x if x
    @robot.y += y if y

    { side: @robot.side }.tap do |hash|
      hash[:x] = x if x
      hash[:y] = y if y
    end
  end

  def west
    min = @robot.brain.min_x?

    raise Errors::Plateau::OutOfLimit.new(@robot, __method__) if min

    step(-1, nil)
  end
end

app/models/plateau.rb
# frozen_string_literal: true

class Plateau
  attr_reader :x, :y

  def initialize(x = 5, y = 5)
    @x = x.to_i
    @y = y.to_i
  end

  def sides
    @sides ||= %i[north east south west]
  end
end

app/models/robot.rb
# frozen_string_literal: true

class Robot
  attr_accessor :plateau, :side, :x, :y
  attr_reader :brain
  attr_reader :gear
  attr_reader :leg
  attr_reader :steps

  def initialize(x = 0, y = 0, side = 'N')
    @brain = Brain.new self
    @gear  = Gear.new self
    @leg   = Leg.new self
    @side  = translate_side side # TODO: spec
    @steps = []
    @x     = x.to_i
    @y     = y.to_i
  end

  def command(name)
    return move if name.casecmp('m').zero?

    turn_to name
  end

  # TODO: spec
  def commands(names)
    names.scan(/./).each do |name|
      command name
    end
  end

  # TODO: spec
  def to_s
    "#{x} #{y} #{side.to_s.chr.upcase}"
  end

  private

  def move
    @steps << leg.move
  rescue Errors::Plateau::OutOfLimit => e
    register_error_step e
  end

  def register_error_step(error)
    @steps << { error: error.to_s, side: side, x: x, y: y }
  end

  # TODO: dirty
  def translate_side(letter)
    {
      e:     :east,
      east:  :east,
      n:     :north,
      north: :north,
      s:     :south,
      south: :south,
      w:     :west,
      west:  :west,
    }[letter.downcase.to_sym]
  end

  def turn_to(direction)
    @steps << @gear.turn_to(direction)
  rescue Errors::Gear::UnknowDirection => e
    register_error_step e
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/maps_controller.rb
# frozen_string_literal: true

class MapsController < ApplicationController
  def explore
    @robot         = Robot.new(*robot_params)
    @robot.plateau = Plateau.new(*plateau_params)

    @robot.commands params[:commands]
  end

  def index; end

  private

  def plateau_params
    [params[:plateau][:x], params[:plateau][:y]]
  end

  def robot_params
    [params[:x], params[:y], params[:side]]
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/plateau_helper.rb
# frozen_string_literal: true

module PlateauHelper
  def sides_select
    %i[north east south west].map do |side|
      [t("plateau.sides.#{side}"), side]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html dir="ltr" lang="<%= I18n.locale %>">
<head>
  <meta charset="utf-8">
  <meta name="description" content="Rover Robots">
  <meta name="keywords" content="rover, robots, ninja">
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="google" content="notranslate">

  <link type="image/x-icon" rel="shortcut icon" href="/favicon.ico" />

  <title><%= t 'app.name' %></title>

  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
</head>
<body>
  <div class="content">
    <%= render 'shared/menu' %>

    <%= yield %>
  </div>
</body>
</html>

app/views/maps/explore.js.erb
var
  params = <%= raw params.to_json %>,
  areaX = params.plateau.x,
  areaY = params.plateau.y,
  name  = params.name,
  side  = params.side,
  steps = <%= raw @robot.steps.to_json %>,
  x     = params.x,
  y     = params.y;

var rover = new Rover($('#map'), x, y, side, areaX, areaY, steps);

rover.create().explore();

app/views/maps/index.html.erb
<div id="map"></div>

<div id="message"></div>

app/views/shared/_menu.html.erb
<aside role="complementary">
  <%= form_tag explore_path, remote: true do %>
    <div class="placeholder">
      <%= label_tag t('robot.name') %>
      <%= text_field_tag :name, :C3P0, placeholder: t('robot.name'), autofocus: true, class: :input %>
    </div>

    <div class="placeholder">
      <%= label_tag t('robot.speed') %>
      <%= text_field_tag :speed, 200, placeholder: t('robot.speed'), autofocus: true, class: :input %>
    </div>

    <div class="placeholder">
      <%= label_tag t('robot.interval') %>
      <%= text_field_tag :interval, 400, placeholder: t('robot.interval'), autofocus: true, class: :input %>
    </div>

    <div class="placeholder">
      <%= label_tag t('robot.position') %>

      <div class="axis">
        <%= number_field_tag :x, 3, placeholder: t('robot.x'), class: :input %>
        <span>x</span>
        <%= number_field_tag :y, 3, placeholder: t('robot.y'), class: :input %>
      </div>
    </div>

    <div class="placeholder">
      <%= label_tag t('robot.side') %>

      <%= select_tag :side, options_for_select(sides_select, :east) %>
    </div>

    <div class="placeholder">
      <%= label_tag t('robot.area') %>

      <div class="area">
        <%= number_field_tag 'plateau[x]', 5, placeholder: t('robot.x'), class: :input %>
        <span>x</span>
        <%= number_field_tag 'plateau[y]', 5, placeholder: t('robot.y'), class: :input %>
      </div>
    </div>

    <div class="placeholder">
      <%= label_tag t('robot.commands') %>

      <%= text_field_tag :commands, :mmrmmrmrrm, placeholder: t('robot.commands'), class: :input %>
    </div>

    <%= button_tag t('robot.buttons.explore'), class: 'button green right' %>
  <% end %>
</aside>